name: Deployement

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          export_environment_variables: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Push docker image to Google Artifact Registry
        run: gcloud builds submit --tag europe-southwest1-docker.pkg.dev/energetica-services/energetica-api/energetica-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy energetica-api-run \
            --image europe-southwest1-docker.pkg.dev/energetica-services/energetica-api/energetica-api:latest \
            --region europe-southwest1 \
            --allow-unauthenticated \
            --project energetica-services \
            --max-instances=4 \
            --set-env-vars GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}",ENERGETICA_DB_CONFIG="${{ secrets.ENERGETICA_DB_CONFIG }}",CELS_DB_CONFIG="${{ secrets.CELS_DB_CONFIG }}"
